### ISSUE TITLE
Global date format: à faire de manière plus élégante...

### ISSUE THREAD

**Issue by nuffer** [sysmoh/intranetBS#97]
Actuellement dans AppExtension => getGlobals() => 'global_date_format' => 'd.m.Y',

Cette variable global servait à definir un format standard des date via |date(global_date_format).

Depuis Sf 2.7 il y la config suivante:

```yml
# in config.yml
# Twig Configuration
twig:
    date:
        format: d.m.Y, H:i:s #=> a convertire dans le meme format que global_date_format
        interval_format: '%%d days'
``` 
Donc il faut viré tout les filtres |date(global_date_format) et les remplacer par |date avec le bon date:format dans la config twig
